server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.php index.html;
        
        include fastcgi_params;
        fastcgi_pass local-app:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
    }

    location /jenkins {
        proxy_pass http://local-jenkins:8080/jenkins;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
